#!/usr/bin/env python3
"""Generate all Token Guard icon variants from assets/icon.svg.

The master SVG uses a green (#10b981) shield with a white "T".
Colored tray variants are generated by swapping the shield fill color.
"""

import os
import sys
from pathlib import Path

import cairosvg
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = ROOT / "assets"
ICONS_DIR = ROOT / "src-tauri" / "icons"
MASTER_SVG = ASSETS_DIR / "icon.svg"

COLORS = {
    "icon": "#10b981",          # emerald-500 (app icon / normal tray)
    "icon_green": "#10b981",    # tray: active/healthy
    "icon_yellow": "#f59e0b",   # tray: warning
    "icon_orange": "#f97316",   # tray: paused
    "icon_red": "#ef4444",      # tray: limit hit
}

APP_SIZES = [32, 128, 256, 512]
TRAY_SIZE = 512
ICO_SIZES = [16, 32, 48, 128, 256]


def render_svg(svg_text: str, size: int, out_path: Path) -> None:
    png_bytes = cairosvg.svg2png(bytestring=svg_text.encode(), output_width=size, output_height=size)
    out_path.write_bytes(png_bytes)


def build_ico(images: list[Path], out_path: Path) -> None:
    pil_images = []
    for img_path in images:
        img = Image.open(img_path)
        # ICO needs square images; ensure palette/RGB is okay.
        if img.mode in ("RGBA", "P"):
            pil_images.append(img)
        else:
            pil_images.append(img.convert("RGBA"))
    pil_images[0].save(
        out_path,
        format="ICO",
        sizes=[(img.width, img.height) for img in pil_images],
        append_images=pil_images[1:],
    )


def main() -> int:
    if not MASTER_SVG.exists():
        print(f"Master icon not found: {MASTER_SVG}", file=sys.stderr)
        return 1

    ICONS_DIR.mkdir(parents=True, exist_ok=True)
    master_text = MASTER_SVG.read_text()

    app_svg = master_text.replace("#10b981", COLORS["icon"])

    # App icon sizes used by Tauri.
    for size in APP_SIZES:
        name = f"{size}x{size}.png"
        if size == 512:
            name = "icon.png"
        render_svg(app_svg, size, ICONS_DIR / name)
        if size == 128:
            render_svg(app_svg, size * 2, ICONS_DIR / "128x128@2x.png")

    # Multi-size ICO for Windows.
    ico_images = []
    for size in ICO_SIZES:
        render_svg(app_svg, size, ICONS_DIR / f"ico_{size}.png")
        ico_images.append(ICONS_DIR / f"ico_{size}.png")
    build_ico(ico_images, ICONS_DIR / "icon.ico")
    for tmp in ICONS_DIR.glob("ico_*.png"):
        tmp.unlink()

    # Colored tray icons (same shape, different fill).
    for base_name, color in COLORS.items():
        if base_name == "icon":
            continue
        colored_svg = master_text.replace("#10b981", color)
        render_svg(colored_svg, TRAY_SIZE, ICONS_DIR / f"{base_name}.png")

    print(f"Icons generated in {ICONS_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
